### ISSUE TITLE
Dragon Adventures - Won't Excecute

### ISSUE THREAD

**Issue by Horredish** [1201for/V.G-Hub#17]
For a little over a while now, when executing the V.G script into DA, the script will load like normal but the GUI won't appear. Synapse shows this error in the console. 
![image](https://user-images.githubusercontent.com/126927160/222863219-f45ca021-52f4-4c2f-b561-be4d6071fa63.png)

**Comment by JakeRuCodes** [comment]
Synapse X doesn't work for right now, I suggest you use Kiwi X/Fluxus/Electron

**Comment by 1201for** [comment]
incorrect
