### ISSUE TITLE
VG Hub loads but wont open

### ISSUE THREAD

**Issue by EKYKing** [1201for/V.G-Hub#19]
Pressing the keybind wont work it doesnt even automatically open like it did it was working fine until today

**Comment by huy50310** [comment]
do you know how to open?

**Comment by EKYKing** [comment]
Yeah you need to use the keyboard script to open otherwise it wouldnt work + it automatically opens when you load the script but it doesnt work somehow it worked till today

**Comment by EKYKing** [comment]
Lemme check if it still works

**Comment by EKYKing** [comment]
Yeah with or without keyboard script still doesnt work

**Comment by 1201for** [comment]
try changing the keybind or check with me in the discord thank bye
