### ISSUE TITLE
Dragon Adventures Crash On injection

### ISSUE THREAD

**Issue by BlazinKing** [1201for/V.G-Hub#21]
Dragon adventures and roblox as a whole crashes whenever I inject the script (using fluxus for refernce) I have uninstalled and reinstalled both fluxus and roblox and am still getting the crash. Was seeing if you could check it out. V/R, Blaze

**Comment by 1201for** [comment]
![](https://cdn.discordapp.com/attachments/1107465247784173578/1146693996110950441/image.png)
